import React from 'react';
import { CardContainer } from './ui/CardContainer';
import { Card } from './ui/Card';
import { CardImage } from './ui/CardImage';
import { CardText } from './ui/CardText';


export class Search extends React.PureComponent {
    render() {
        return (
            <div>
                <h2>Műfajok böngészése</h2>
                <CardContainer>
                    <Card>
                        <CardImage></CardImage>
                        <CardText>
                            <h4>Műfaj</h4>
                        </CardText>
                    </Card>
                    <Card>
                        <CardImage></CardImage>
                        <CardText>
                            <h4>Műfaj</h4>
                        </CardText>
                    </Card>
                    <Card>
                        <CardImage></CardImage>
                        <CardText>
                            <h4>Műfaj</h4>
                        </CardText>
                    </Card>
                    <Card>
                        <CardImage></CardImage>
                        <CardText>
                            <h4>Műfaj</h4>
                        </CardText>
                    </Card>
                </CardContainer>
                <CardContainer>
                    <Card>
                        <CardImage></CardImage>
                        <CardText>
                            <h4>Műfaj</h4>
                        </CardText>
                    </Card>
                    <Card>
                        <CardImage></CardImage>
                        <CardText>
                            <h4>Műfaj</h4>
                        </CardText>
                    </Card>
                    <Card>
                        <CardImage></CardImage>
                        <CardText>
                            <h4>Műfaj</h4>
                        </CardText>
                    </Card>
                    <Card>
                        <CardImage></CardImage>
                        <CardText>
                            <h4>Műfaj</h4>
                        </CardText>
                    </Card>
                </CardContainer>
                <CardContainer>
                    <Card>
                        <CardImage></CardImage>
                        <CardText>
                            <h4>Műfaj</h4>
                        </CardText>
                    </Card>
                    <Card>
                        <CardImage></CardImage>
                        <CardText>
                            <h4>Műfaj</h4>
                        </CardText>
                    </Card>
                    <Card>
                        <CardImage></CardImage>
                        <CardText>
                            <h4>Műfaj</h4>
                        </CardText>
                    </Card>
                    <Card>
                        <CardImage></CardImage>
                        <CardText>
                            <h4>Műfaj</h4>
                        </CardText>
                    </Card>
                </CardContainer>
                <CardContainer>
                    <Card>
                        <CardImage></CardImage>
                        <CardText>
                            <h4>Műfaj</h4>
                        </CardText>
                    </Card>
                    <Card>
                        <CardImage></CardImage>
                        <CardText>
                            <h4>Műfaj</h4>
                        </CardText>
                    </Card>
                    <Card>
                        <CardImage></CardImage>
                        <CardText>
                            <h4>Műfaj</h4>
                        </CardText>
                    </Card>
                    <Card>
                        <CardImage></CardImage>
                        <CardText>
                            <h4>Műfaj</h4>
                        </CardText>
                    </Card>
                </CardContainer>
            </div>
        )
    }
}